import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const docsDir = path.join(process.cwd(), 'docs');

// 获取Markdown文件的order值
function getOrderFromMd(filePath: string): number {
	try {
		if (fs.existsSync(filePath)) {
			const content = fs.readFileSync(filePath, 'utf-8');
			const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
			if (frontmatterMatch) {
				const frontmatter = frontmatterMatch[1];
				const orderMatch = frontmatter.match(/order:\s*(\d+)/);
				if (orderMatch) {
					return parseInt(orderMatch[1], 10);
				}
			}
		}
	} catch (error) {
		console.warn(`读取文件order失败: ${filePath}`, error);
	}
	return Infinity;
}

// 获取 showList 配置
function getShowListFromMd(filePath: string): boolean {
	try {
		if (fs.existsSync(filePath)) {
			const content = fs.readFileSync(filePath, 'utf-8');
			const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
			if (frontmatterMatch) {
				const frontmatter = frontmatterMatch[1];
				const showListMatch = frontmatter.match(/showList:\s*(true|false)/);
				if (showListMatch) {
					return showListMatch[1] === 'true';
				}
			}
		}
	} catch (error) {
		console.warn(`读取文件showList失败: ${filePath}`, error);
	}
	return false;
}

// 检查文件是否可以被自动生成覆盖（文件不存在或带有 autoGenerated: true 标记）
function canOverwrite(filePath: string): boolean {
	try {
		if (!fs.existsSync(filePath)) {
			// 文件不存在，可以生成
			return true;
		}
		
		const content = fs.readFileSync(filePath, 'utf-8');
		const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
		if (frontmatterMatch) {
			const frontmatter = frontmatterMatch[1];
			const autoGenMatch = frontmatter.match(/autoGenerated:\s*(true|false)/);
			if (autoGenMatch) {
				// 如果有 autoGenerated 标记，根据其值决定
				return autoGenMatch[1] === 'true';
			}
		}
		
		// 文件存在但没有 autoGenerated 标记，不覆盖（保护手动创建的文件）
		return false;
	} catch (error) {
		console.warn(`检查文件是否可覆盖失败: ${filePath}`, error);
		return false;
	}
}

// 获取Markdown文件的标题
function getTitleFromMd(filePath: string): string {
	try {
		if (fs.existsSync(filePath)) {
			const content = fs.readFileSync(filePath, 'utf-8');
			
			// 先尝试从frontmatter获取标题
			const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
			if (frontmatterMatch) {
				const frontmatter = frontmatterMatch[1];
				const titleMatch = frontmatter.match(/title:\s*(.*)/);
				if (titleMatch) {
					return titleMatch[1].trim().replace(/['"]/g, '');
				}
			}
			
			// 如果frontmatter没有标题，尝试获取第一个h1标题
			const h1Match = content.match(/^#\s+(.*)$/m);
			if (h1Match) {
				return h1Match[1].trim();
			}
		}
	} catch (error) {
		console.warn(`读取文件标题失败: ${filePath}`, error);
	}
	
	return '';
}

// 获取目录显示名称
function getDirectoryDisplayName(dirPath: string, dirName: string): string {
	const indexPath = path.join(dirPath, 'index.md');
	const title = getTitleFromMd(indexPath);
	return title || dirName;
}

// 获取目录下的markdown文件
function getMarkdownFiles(dirPath: string, relativePath: string): { name: string; displayName: string; link: string; order: number }[] {
	const files = fs.readdirSync(dirPath).filter(file => 
		file.endsWith('.md') && 
		file !== 'index.md' && 
		!file.startsWith('.')
	);

	return files.map(file => {
		const filePath = path.join(dirPath, file);
		const displayName = getTitleFromMd(filePath) || file.replace('.md', '');
		const order = getOrderFromMd(filePath);
		const link = `${relativePath}/${file.replace('.md', '')}`;
		
		return {
			name: file,
			displayName,
			link,
			order
		};
	});
}

// 分类图标映射
const categoryIconMap: Record<string, string> = {
	'beginner': '🌱',
	'intermediate': '🌿',
	'advanced': '🌳',
	'project': '🚀',
	'tutorial': '📚',
	'language': '💻',
	'default': '📁'
};

async function genIndex() {
	console.log('开始生成索引');

	// 查询一级目录列表
	const firstLevelDirs = fs.readdirSync(docsDir).filter(dir => 
		fs.statSync(path.join(docsDir, dir)).isDirectory() && 
		!dir.startsWith('.') && 
		dir !== 'public'
	);

	console.log("一级目录: " + firstLevelDirs);

	// 遍历每个一级目录
	for (const firstDir of firstLevelDirs) {
		const firstDirPath = path.join(docsDir, firstDir);
		
		// 查询二级目录列表（知识库）
		const secondLevelDirs = fs.readdirSync(firstDirPath).filter(dir => 
			fs.statSync(path.join(firstDirPath, dir)).isDirectory() && 
			!dir.startsWith('.')
		);

		console.log(`${firstDir} 下的知识库目录: ` + secondLevelDirs);

		// 遍历每个知识库目录（二级目录）
		for (const knowledgeBase of secondLevelDirs) {
			const knowledgeBasePath = path.join(firstDirPath, knowledgeBase);
			console.log(`处理知识库: ${firstDir}/${knowledgeBase}`);
			
			if (!fs.existsSync(knowledgeBasePath)) {
				console.log(`目录 ${knowledgeBasePath} 不存在，跳过`);
				continue;
			}

			// 获取二级目录的显示名称
			const secondLevelDisplayName = getDirectoryDisplayName(knowledgeBasePath, knowledgeBase);
			
			// 检查是否已存在 index.md 并读取 showList 配置
			const indexPath = path.join(knowledgeBasePath, 'index.md');
			const showList = getShowListFromMd(indexPath);
			
			console.log(`${firstDir}/${knowledgeBase} showList: ${showList}`);

			// 查询三级目录列表
			const thirdLevelDirs = fs.readdirSync(knowledgeBasePath).filter(dir => 
				fs.statSync(path.join(knowledgeBasePath, dir)).isDirectory() && 
				!dir.startsWith('.')
			);

			// 获取二级目录下的markdown文件
			const secondLevelMarkdownFiles = getMarkdownFiles(knowledgeBasePath, `/${firstDir}/${knowledgeBase}`);
			
			const columns: any[] = [];

			// 处理三级目录
			for (const thirdDir of thirdLevelDirs) {
				const thirdDirPath = path.join(knowledgeBasePath, thirdDir);
				const thirdDisplayName = getDirectoryDisplayName(thirdDirPath, thirdDir);
				const thirdOrder = getOrderFromMd(path.join(thirdDirPath, 'index.md'));
				const categoryIcon = categoryIconMap[thirdDir] || categoryIconMap['default'];

				// 获取三级目录下的markdown文件
				const thirdLevelMarkdownFiles = getMarkdownFiles(thirdDirPath, `/${firstDir}/${knowledgeBase}/${thirdDir}`);
				
				// 获取四级目录（如果存在）
				const fourthLevelDirs = fs.readdirSync(thirdDirPath).filter(dir => 
					fs.statSync(path.join(thirdDirPath, dir)).isDirectory() && 
					!dir.startsWith('.')
				);

				const fourthLevelItems = fourthLevelDirs.map(fourthDir => {
					const fourthDirPath = path.join(thirdDirPath, fourthDir);
					const fourthIndexPath = path.join(fourthDirPath, 'index.md');
					const fourthDisplayName = getDirectoryDisplayName(fourthDirPath, fourthDir);
					const fourthOrder = getOrderFromMd(fourthIndexPath);
					
					return {
						displayName: fourthDisplayName,
						link: `/${firstDir}/${knowledgeBase}/${thirdDir}/${fourthDir}/`,
						order: fourthOrder
					};
				});

				// 根据 showList 决定是否包含文件
				let allItems;
				if (showList) {
					// showList: true - 展示所有内容（文件+目录）
					allItems = [
						...thirdLevelMarkdownFiles.map(f => ({ displayName: f.displayName, link: f.link, order: f.order })),
						...fourthLevelItems
					].sort((a, b) => a.order - b.order);
				} else {
					// 没有 showList - 只展示目录，但如果没有子目录，则展示文件
					if (fourthLevelItems.length > 0) {
						allItems = fourthLevelItems.sort((a, b) => a.order - b.order);
					} else {
						// 没有子目录，展示文件
						allItems = thirdLevelMarkdownFiles.map(f => ({ displayName: f.displayName, link: f.link, order: f.order })).sort((a, b) => a.order - b.order);
					}
				}

				if (allItems.length > 0) {
					columns.push({
						id: thirdDir,
						icon: categoryIcon,
						title: thirdDisplayName,
						order: thirdOrder,
						items: allItems
					});
				}
			}

			// 当 showList: true 且有三级目录时，将三级目录本身作为单列展示
			if (showList && thirdLevelDirs.length > 0) {
				// 重新构建 columns，把三级目录展示为一列
				const thirdDirItems = thirdLevelDirs.map(thirdDir => {
					const thirdDirPath = path.join(knowledgeBasePath, thirdDir);
					const thirdDisplayName = getDirectoryDisplayName(thirdDirPath, thirdDir);
					const thirdOrder = getOrderFromMd(path.join(thirdDirPath, 'index.md'));
					
					return {
						displayName: thirdDisplayName,
						link: `/${firstDir}/${knowledgeBase}/${thirdDir}/`,
						order: thirdOrder
					};
				}).sort((a, b) => a.order - b.order);

				// 清空之前的 columns，用新的结构
				columns.length = 0;
				columns.push({
					id: 'directories',
					icon: '📚',
					title: '教程列表',
					order: -1,
					items: thirdDirItems
				});
			}

			// 如果二级目录下有markdown文件，根据 showList 决定是否展示
			if (showList && secondLevelMarkdownFiles.length > 0) {
				columns.push({
					id: 'files',
					icon: '📝',
					title: '文档',
					order: -1, // 放在最前面
					items: secondLevelMarkdownFiles.map(f => ({ displayName: f.displayName, link: f.link }))
				});
			}

			// 按order排序
			columns.sort((a, b) => a.order - b.order);

			if (columns.length === 0) {
				console.log(`知识库 ${firstDir}/${knowledgeBase} 为空，跳过`);
				continue;
			}

			// 准备页面数据
			const pageData = {
				hero: {
					title: secondLevelDisplayName,
					description: `${secondLevelDisplayName}的内容概览`
				},
				columns: columns.map(col => ({
					id: col.id,
					icon: col.icon,
					title: col.title,
					items: col.items
				}))
			};

			// 检查是否可以覆盖该文件
			if (!canOverwrite(indexPath)) {
				console.log(`跳过 ${indexPath} - 文件存在且未标记为自动生成`);
				continue;
			}

			// 根据 showList 生成不同格式的 index.md
			let indexContent;
			if (showList) {
				// showList: true - 使用 HomePage 格式，隐藏侧边栏，展示所有内容
				indexContent = `---
title: ${secondLevelDisplayName}
order: 1
editLink: false
isHomePage: true
sidebar: false
showList: true
autoGenerated: true
---

<script setup>
const pageData = ${JSON.stringify(pageData, null, 2)};
</script>

<HomePage :hero="pageData.hero" :columns="pageData.columns" />
`;
			} else {
				// 没有 showList - 只展示目录，保留侧边栏
				indexContent = `---
title: ${secondLevelDisplayName}
order: 1
editLink: false
isHomePage: true
autoGenerated: true
---

<script setup>
const pageData = ${JSON.stringify(pageData, null, 2)};
</script>

<HomePage :hero="pageData.hero" :columns="pageData.columns" />
`;
			}
			
			// 打印并写入文件
			console.log("indexPath: " + indexPath);
			fs.writeFileSync(indexPath, indexContent);
		}
	}
	
	console.log('索引生成完成');
}

genIndex().catch(console.error);
