name: Build Documentation

on:
  push:
    branches:
      - main  # 修改为你的主分支名称

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Example Step
        run: |
          echo "The value of MY_SECRET is: ${{ secrets.DEMO }}"
          
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # 修改为你需要的Node.js版本
          
      - name: Install dependencies esbuild
        run: npm install --save-dev esbuild
        
      - name: Build documentation
        run: npm run docs:build
    
      - name: upload files to OSS
        uses: walihome/logan_upload_aliyun_oss@v1.0.4
        with:
            accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
            accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
            bucket: dooocs
            # use your own endpoint
            endpoint: oss-cn-hangzhou.aliyuncs.com
            folder: docs/.vitepress/dist/
            ossDir: doc/
